name: 👯‍♂️ Style Changing Request
description: Suggest a style design
title: '[style]: '
labels: ["✨ goal: improvement","🚦status: awaiting triage","🕹 aspect: interface"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this template!
  - type: textarea
    id: style-idea
    attributes:
      label: What's the style idea?
      placeholder: Add descriptions
     
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      
      placeholder: Add screenshots
      
  - type: checkboxes
    id: terms
    attributes:
      label: "Record"
      
      options:
        - label: I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues)
          required: true
          
        - label: I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)
          required: true

        - label: I agree to follow this project's [Code of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
          required: true

        

        - label: I want to work on this issue