name: ​Task Request
description: This is Only For Project Admins and Mentors.
title: " <write a small description here>"
labels: ["priority: high"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: Please add screenshots if required
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional Details?
      description: Please Provide Key Details, if required (Goals and objectives,Deliverables,Dependencies)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Deadline
      description: Specify the task deadline
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Stay you can start working on it by taking latest pull from main branch

      
  Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).

      
   Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)

   
   Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins

   
   **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)

   
   The changes don't break the code

        
   Please attach the screenshots and video of the development work once it is done 

       
   If you need any help please join the default  ([Google Meet Link](https://meet.google.com/bwp-aasw-xbk))"
     
      
 
